@startuml

state O_Null
state Authorize_Origination_Attempt
state Collect_Information
state Analyse_Information {
	state Collected_Info <<inputPin>>
}
state Routing {
	state Analysed_Information <<inputPin>>
}
state O_Alerting {
	state O_Term_Seized <<inputPin>>
}
state O_Active {
	state O_Answer <<inputPin>>
}
state O_Exception

O_Null -down-> Authorize_Origination_Attempt
Authorize_Origination_Attempt -down-> Collect_Information
Collect_Information -down-> Collected_Info
Analyse_Information -down-> Analysed_Information
Routing -down-> O_Term_Seized
O_Alerting -down-> O_Answer

O_Exception -left-> O_Null
Analyse_Information -up-> O_Exception : invalid_information
Routing -up-> O_Exception : O_routing_failure
O_Alerting -up-> O_Exception : O_alerting_failure

@enduml

