@startuml

state null {
}
state authorize_origination_attempt {
}
state collect_information {
}
state analyse_information {
}
state routing {
}
state active {
}

[*] --> null : CCR
null --> authorize_origination_attempt : originating
null --> [*]

authorize_origination_attempt --> collect_information : CCR-I RSU
authorize_origination_attempt --> collect_information : CCR-U RSU
authorize_origination_attempt --> analyse_information : CCR-I RSU called
authorize_origination_attempt --> analyse_information : CCR-U RSU called
authorize_origination_attempt --> authorize_origination_attempt : CCR-I
authorize_origination_attempt --> authorize_origination_attempt : CCR-U
authorize_origination_attempt --> null : CCR-T

collect_information --> analyse_information : CCR-U RSU called
collect_information --> collect_information : CCR-U 
collect_information --> null : CCR-T

analyse_information --> active : CCR-U USU
analyse_information --> routing : CCR-U
analyse_information --> null : CCR-T

routing --> active : CCR-U USU
routing --> routing : CCR-U
routing --> null : CCR-T

active --> null : CCR-T
active --> active : CCR-U

@enduml
