@startuml

hide empty description
skinparam shadowing false
state null #white ##f57f17
state authorize_event_attempt #white ##f57f17
state collect_information #white##f57f17
state analyse_information #white##f57f17
state active #white ##f57f17

[*] --> null : CCR
null --> authorize_event_attempt : CCR
null --> [*]

authorize_event_attempt --> null : One-Time
authorize_event_attempt --> analyse_information : Success & Granted
authorize_event_attempt --> collect_information : Success
authorize_event_attempt --> null : Fail | Terminate

collect_information --> active : Success & Used
collect_information --> analyse_information : Success & Recipient
collect_information --> collect_information : *
collect_information --> null : Terminate

analyse_information --> active : Success & Used
analyse_information --> analyse_information : *
analyse_information --> null : Terminate

active --> active : *
active --> null : Terminate

@enduml
