@startuml

hide empty description
skinparam shadowing false
state null #white ##f57f17
state authorize_origination_attempt #white ##f57f17
state terminating_call_handling #white ##f57f17
state collect_information #white ##f57f17
state analyse_information #white ##f57f17
state o_alerting #white ##f57f17
state t_alerting #white ##f57f17
state active #white ##f57f17

[*] --> null : CCR
null --> authorize_origination_attempt : CCR & Originating
null --> terminating_call_handling : CCR & Terminating
null --> [*]

authorize_origination_attempt --> analyse_information : Success & Destination
authorize_origination_attempt --> collect_information : Success
authorize_origination_attempt --> null : Fail | Terminate

terminating_call_handling --> t_alerting : Success & Granted
terminating_call_handling --> active : Success & Used
terminating_call_handling --> terminating_call_handling : Success
terminating_call_handling --> null : Fail | Terminate

collect_information --> o_alerting : Success & Granted
collect_information --> analyse_information : Success & Destination
collect_information --> active : Success & Used
collect_information --> collect_information : *
collect_information --> null : Terminate

analyse_information --> active : Success & Used
analyse_information --> o_alerting: Success & Granted
analyse_information --> analyse_information : *
analyse_information --> null : Terminate

o_alerting --> active : Success + Used
o_alerting --> o_alerting : *
o_alerting --> null : Terminate

t_alerting --> active : Success & Used
t_alerting --> t_alerting : *
t_alerting --> null : Terminate

active --> active : *
active --> null : Terminate

@enduml
